### ISSUE TITLE
quick not working

### ISSUE THREAD

**Issue by mehrabali** [surveycto/search-select-one#8]
I was trying to combine the ``search-select-one`` plug-in with the search() function and quick appearance. But, this is not working and throwing an error. This is the appearance I used: ``search('india_list', 'matches', 'state_code', ${state_code}) quick custom-search-select-one``
![quick-error](https://user-images.githubusercontent.com/52687943/116970476-e2ed1100-acd9-11eb-8ee7-848b320a4de5.jpg)

**Comment by cking0987** [comment]
@mehrabali sorry about that. I found the issue and pushed a fix. Just waiting on a code review now before merging into the production branch. If you want to try it out, you can download it here: https://github.com/surveycto/search-select-one/raw/fixes-%238/search-select-one.fieldplugin.zip
